// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: gcpemulators/gcpemulatorspb/cloudtasksemulator.proto

package gcpemulatorspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GcpEmulator_Readiness_FullMethodName = "/gcpemulatorspb.GcpEmulator/Readiness"
	GcpEmulator_Stop_FullMethodName      = "/gcpemulatorspb.GcpEmulator/Stop"
)

// GcpEmulatorClient is the client API for GcpEmulator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CloudTasksEmulatorService provides control and health check methods for the Cloud Tasks emulator.
type GcpEmulatorClient interface {
	// Readiness checks if the emulator is ready to accept requests.
	// Returns the readiness status of the emulator.
	Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error)
	// Stop gracefully stops the emulator.
	// Returns success when the emulator has been stopped.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type gcpEmulatorClient struct {
	cc grpc.ClientConnInterface
}

func NewGcpEmulatorClient(cc grpc.ClientConnInterface) GcpEmulatorClient {
	return &gcpEmulatorClient{cc}
}

func (c *gcpEmulatorClient) Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadinessResponse)
	err := c.cc.Invoke(ctx, GcpEmulator_Readiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gcpEmulatorClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, GcpEmulator_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GcpEmulatorServer is the server API for GcpEmulator service.
// All implementations must embed UnimplementedGcpEmulatorServer
// for forward compatibility.
//
// CloudTasksEmulatorService provides control and health check methods for the Cloud Tasks emulator.
type GcpEmulatorServer interface {
	// Readiness checks if the emulator is ready to accept requests.
	// Returns the readiness status of the emulator.
	Readiness(context.Context, *ReadinessRequest) (*ReadinessResponse, error)
	// Stop gracefully stops the emulator.
	// Returns success when the emulator has been stopped.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedGcpEmulatorServer()
}

// UnimplementedGcpEmulatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGcpEmulatorServer struct{}

func (UnimplementedGcpEmulatorServer) Readiness(context.Context, *ReadinessRequest) (*ReadinessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Readiness not implemented")
}
func (UnimplementedGcpEmulatorServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedGcpEmulatorServer) mustEmbedUnimplementedGcpEmulatorServer() {}
func (UnimplementedGcpEmulatorServer) testEmbeddedByValue()                     {}

// UnsafeGcpEmulatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GcpEmulatorServer will
// result in compilation errors.
type UnsafeGcpEmulatorServer interface {
	mustEmbedUnimplementedGcpEmulatorServer()
}

func RegisterGcpEmulatorServer(s grpc.ServiceRegistrar, srv GcpEmulatorServer) {
	// If the following call panics, it indicates UnimplementedGcpEmulatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GcpEmulator_ServiceDesc, srv)
}

func _GcpEmulator_Readiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GcpEmulatorServer).Readiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GcpEmulator_Readiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GcpEmulatorServer).Readiness(ctx, req.(*ReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GcpEmulator_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GcpEmulatorServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GcpEmulator_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GcpEmulatorServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GcpEmulator_ServiceDesc is the grpc.ServiceDesc for GcpEmulator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GcpEmulator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gcpemulatorspb.GcpEmulator",
	HandlerType: (*GcpEmulatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Readiness",
			Handler:    _GcpEmulator_Readiness_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _GcpEmulator_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gcpemulators/gcpemulatorspb/cloudtasksemulator.proto",
}
