// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gcpemulators/gcpemulatorspb/cloudtasksemulator.proto

package gcpemulatorspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadinessRequest is an empty request for checking emulator readiness.
type ReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessRequest) Reset() {
	*x = ReadinessRequest{}
	mi := &file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessRequest) ProtoMessage() {}

func (x *ReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessRequest.ProtoReflect.Descriptor instead.
func (*ReadinessRequest) Descriptor() ([]byte, []int) {
	return file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDescGZIP(), []int{0}
}

// ReadinessResponse contains the readiness status of the emulator.
type ReadinessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ready indicates whether the emulator is ready to accept requests.
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// message provides additional information about the readiness status.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessResponse) Reset() {
	*x = ReadinessResponse{}
	mi := &file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessResponse) ProtoMessage() {}

func (x *ReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessResponse.ProtoReflect.Descriptor instead.
func (*ReadinessResponse) Descriptor() ([]byte, []int) {
	return file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDescGZIP(), []int{1}
}

func (x *ReadinessResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadinessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StopRequest is an empty request for stopping the emulator.
type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDescGZIP(), []int{2}
}

// StopResponse contains the result of stopping the emulator.
type StopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the emulator was stopped successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message provides additional information about the stop operation.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDescGZIP(), []int{3}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto protoreflect.FileDescriptor

const file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDesc = "" +
	"\n" +
	"4gcpemulators/gcpemulatorspb/cloudtasksemulator.proto\x12\x0egcpemulatorspb\"\x12\n" +
	"\x10ReadinessRequest\"C\n" +
	"\x11ReadinessResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vStopRequest\"B\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2_\n" +
	"\vGcpEmulator\x12P\n" +
	"\tReadiness\x12 .gcpemulatorspb.ReadinessRequest\x1a!.gcpemulatorspb.ReadinessResponseBCZAgithub.com/nolanrsherman/gcpemulators/gcpemulators/gcpemulatorspbb\x06proto3"

var (
	file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDescOnce sync.Once
	file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDescData []byte
)

func file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDescGZIP() []byte {
	file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDescOnce.Do(func() {
		file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDesc), len(file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDesc)))
	})
	return file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDescData
}

var file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_goTypes = []any{
	(*ReadinessRequest)(nil),  // 0: gcpemulatorspb.ReadinessRequest
	(*ReadinessResponse)(nil), // 1: gcpemulatorspb.ReadinessResponse
	(*StopRequest)(nil),       // 2: gcpemulatorspb.StopRequest
	(*StopResponse)(nil),      // 3: gcpemulatorspb.StopResponse
}
var file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_depIdxs = []int32{
	0, // 0: gcpemulatorspb.GcpEmulator.Readiness:input_type -> gcpemulatorspb.ReadinessRequest
	1, // 1: gcpemulatorspb.GcpEmulator.Readiness:output_type -> gcpemulatorspb.ReadinessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_init() }
func file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_init() {
	if File_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDesc), len(file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_goTypes,
		DependencyIndexes: file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_depIdxs,
		MessageInfos:      file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_msgTypes,
	}.Build()
	File_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto = out.File
	file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_goTypes = nil
	file_gcpemulators_gcpemulatorspb_cloudtasksemulator_proto_depIdxs = nil
}
