// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: cloudtaskemulator/cloudtasksemulatorpb/cloudtasksemulator.proto

package cloudtasksemulatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudTasksEmulatorService_Readiness_FullMethodName = "/cloudtasksemulatorpb.CloudTasksEmulatorService/Readiness"
	CloudTasksEmulatorService_Stop_FullMethodName      = "/cloudtasksemulatorpb.CloudTasksEmulatorService/Stop"
)

// CloudTasksEmulatorServiceClient is the client API for CloudTasksEmulatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CloudTasksEmulatorService provides control and health check methods for the Cloud Tasks emulator.
type CloudTasksEmulatorServiceClient interface {
	// Readiness checks if the emulator is ready to accept requests.
	// Returns the readiness status of the emulator.
	Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error)
	// Stop gracefully stops the emulator.
	// Returns success when the emulator has been stopped.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type cloudTasksEmulatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudTasksEmulatorServiceClient(cc grpc.ClientConnInterface) CloudTasksEmulatorServiceClient {
	return &cloudTasksEmulatorServiceClient{cc}
}

func (c *cloudTasksEmulatorServiceClient) Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadinessResponse)
	err := c.cc.Invoke(ctx, CloudTasksEmulatorService_Readiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudTasksEmulatorServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, CloudTasksEmulatorService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudTasksEmulatorServiceServer is the server API for CloudTasksEmulatorService service.
// All implementations must embed UnimplementedCloudTasksEmulatorServiceServer
// for forward compatibility.
//
// CloudTasksEmulatorService provides control and health check methods for the Cloud Tasks emulator.
type CloudTasksEmulatorServiceServer interface {
	// Readiness checks if the emulator is ready to accept requests.
	// Returns the readiness status of the emulator.
	Readiness(context.Context, *ReadinessRequest) (*ReadinessResponse, error)
	// Stop gracefully stops the emulator.
	// Returns success when the emulator has been stopped.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedCloudTasksEmulatorServiceServer()
}

// UnimplementedCloudTasksEmulatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudTasksEmulatorServiceServer struct{}

func (UnimplementedCloudTasksEmulatorServiceServer) Readiness(context.Context, *ReadinessRequest) (*ReadinessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Readiness not implemented")
}
func (UnimplementedCloudTasksEmulatorServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedCloudTasksEmulatorServiceServer) mustEmbedUnimplementedCloudTasksEmulatorServiceServer() {
}
func (UnimplementedCloudTasksEmulatorServiceServer) testEmbeddedByValue() {}

// UnsafeCloudTasksEmulatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudTasksEmulatorServiceServer will
// result in compilation errors.
type UnsafeCloudTasksEmulatorServiceServer interface {
	mustEmbedUnimplementedCloudTasksEmulatorServiceServer()
}

func RegisterCloudTasksEmulatorServiceServer(s grpc.ServiceRegistrar, srv CloudTasksEmulatorServiceServer) {
	// If the following call panics, it indicates UnimplementedCloudTasksEmulatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudTasksEmulatorService_ServiceDesc, srv)
}

func _CloudTasksEmulatorService_Readiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudTasksEmulatorServiceServer).Readiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudTasksEmulatorService_Readiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudTasksEmulatorServiceServer).Readiness(ctx, req.(*ReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudTasksEmulatorService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudTasksEmulatorServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudTasksEmulatorService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudTasksEmulatorServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudTasksEmulatorService_ServiceDesc is the grpc.ServiceDesc for CloudTasksEmulatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudTasksEmulatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudtasksemulatorpb.CloudTasksEmulatorService",
	HandlerType: (*CloudTasksEmulatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Readiness",
			Handler:    _CloudTasksEmulatorService_Readiness_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _CloudTasksEmulatorService_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloudtaskemulator/cloudtasksemulatorpb/cloudtasksemulator.proto",
}
